Repository gbdev/rgbds, pull requests merged in 2021-05, with the labels that each got.

#865 Parse 'ld hl, sp - <e8>' correctly
  src/asm/parser.y
  test/link/all-instructions.asm
  test/link/all-instructions.out.bin
Labels: bug, rgbasm

#874 Fix `OPT L` and implement `OPT h`
  src/asm/opt.c
  src/asm/rgbasm.5
  test/asm/opt.asm
  test/asm/opt.err
  test/asm/opt.out.bin
Labels: bug, enhancement, rgbasm

#834 Enable address sanitizer in develop builds
  CMakeLists.txt
  Makefile
  src/asm/main.c
  src/link/main.c
Labels: meta, tests

#868 Add TPP1 support
  src/fix/main.c
  src/fix/rgbfix.1
  test/fix/tpp1-bad-major.bin
  test/fix/tpp1-bad-major.err
  test/fix/tpp1-bad-major.flags
  test/fix/tpp1-bad-minor.bin
  test/fix/tpp1-bad-minor.err
  test/fix/tpp1-bad-minor.flags
  test/fix/tpp1-nonjap.bin
  test/fix/tpp1-nonjap.err
  test/fix/tpp1-nonjap.flags
  test/fix/tpp1-nonjap.gb
  test/fix/tpp1-too-short.bin
  test/fix/tpp1-too-short.err
  test/fix/tpp1-too-short.flags
  test/fix/tpp1-unk-major.bin
  test/fix/tpp1-unk-major.err
  test/fix/tpp1-unk-major.flags
  test/fix/tpp1-unk-minor.bin
  test/fix/tpp1-unk-minor.err
  test/fix/tpp1-unk-minor.flags
Labels: enhancement, rgbfix

#876 Output all SECTION UNION/FRAGMENT symbols in .sym files
  src/link/output.c
Labels: bug, rgblink

#875 rgblink adjusts patches' PC offsets when merging FRAGMENTs
  src/link/section.c
  test/link/section-fragment/jr-offset-load/a.asm
  test/link/section-fragment/jr-offset-load/b.asm
  test/link/section-fragment/jr-offset-load/ref.out.bin
  test/link/section-fragment/jr-offset/a.asm
  test/link/section-fragment/jr-offset/b.asm
  test/link/section-fragment/jr-offset/ref.out.bin
  test/link/test.sh
Labels: bug, rgblink

#877 Make SECTION size overflow non-fatal
  include/helpers.h
  src/asm/section.c
  test/asm/load-overflow.asm
  test/asm/load-overflow.err
Labels: enhancement, rgbasm

#884 Fix `-Wformat` build warnings on macOS
  Makefile
  src/link/assign.c
  src/link/output.c
  src/link/section.c
Labels: bug, rgblink

#892 Allow error messages for subsequent syntax errors
  src/asm/parser.y
  test/asm/label-macro-arg.err
  test/asm/syntax-error-after-syntax-error.asm
  test/asm/syntax-error-after-syntax-error.err
  test/asm/syntax-error-after-syntax-error.out
  test/asm/syntax-error-after-syntax-error.simple.err
Labels: bug, rgbasm

#893 Syntax error message hints to indent macro invocations
  src/asm/parser.y
  test/asm/syntax-error-after-syntax-error.err
  test/asm/syntax-error-after-syntax-error.simple.err
Labels: enhancement, rgbasm
