Repository gbdev/rgbds, pull requests merged in 2021-04, with the labels that each got.

#825 Define `__RGBDS_VERSION__` as the output of `rgbasm --version` (sans "rgbasm")
  src/asm/rgbasm.5
  src/asm/symbol.c
  test/asm/test.sh
Labels: enhancement, rgbasm

#820 Refactor the lexer's `lookupExpansion` macro to not need `LOOKUP_PRE/POST_NEST`
  src/asm/lexer.c
Labels: refactoring, rgbasm

#829 New lexer 2½: store expansions from the inside out
  src/asm/lexer.c
  test/asm/nested-expansions.asm
  test/asm/nested-expansions.err
  test/asm/nested-expansions.out
Labels: refactoring, rgbasm

#835 Add an .editorconfig
  .editorconfig
Labels: enhancement, meta

#838 Fix interpolation/STRFMT overflow issues
  include/asm/format.h
  src/asm/format.c
  src/asm/rgbasm.5
  test/asm/format-truncation.asm
  test/asm/format-truncation.err
  test/asm/format-truncation.out
  test/asm/interpolation-overflow.asm
  test/asm/interpolation-overflow.err
  test/asm/interpolation-overflow.out
Labels: bug, rgbasm

#839 Fix expansions that start from the end of another expansion
  src/asm/lexer.c
  test/asm/equs-newline.err
  test/asm/equs-recursion.asm
  test/asm/interpolation-recursion.asm
  test/asm/interpolation-recursion.err
  test/asm/rst.asm
  test/asm/test.sh
  test/asm/unique-id.err
  test/link/rst.asm
Labels: bug, rgbasm

#766 Implement SIZEOF("Section") and STARTOF("Section")
  include/asm/rpn.h
  include/linkdefs.h
  src/asm/lexer.c
  src/asm/output.c
  src/asm/parser.y
  src/asm/rgbasm.5
  src/asm/rpn.c
  src/link/patch.c
  src/rgbds.5
  test/asm/section-sizeof-startof.asm
  test/asm/section-sizeof-startof.err
  test/asm/section-sizeof-startof.out
  test/link/sizeof-startof.asm
  test/link/sizeof-startof.out.bin
Labels: enhancement, rgbasm, rgblink

#843 STRSUB and CHARSUB allow negative positions and optional lengths
  src/asm/parser.y
  src/asm/rgbasm.5
  test/asm/charlen-charsub.asm
  test/asm/strsub.asm
  test/asm/strsub.err
  test/asm/strsub.out
Labels: enhancement, rgbasm

#855 Fix compiler warnings
  src/fix/main.c
Labels: bug, refactoring

#861 Updated RGBFIX to report when non-zero bytes are overwritten
  src/fix/main.c
  test/fix/bad-fix-char.err
  test/fix/color.err
  test/fix/compatible.err
  test/fix/fix-override.err
  test/fix/gameid-trunc.err
  test/fix/gameid.err
  test/fix/header-edit.err
  test/fix/header-trash.err
  test/fix/header.err
  test/fix/jp.err
  test/fix/logo-trash.err
  test/fix/logo.err
  test/fix/mbc.err
  test/fix/mbcless-ram.err
  test/fix/new-lic-trunc.err
  test/fix/new-lic.err
  test/fix/old-lic-hex.err
  test/fix/old-lic.err
  test/fix/ram.err
  test/fix/ramful-mbc-no-ram.err
  test/fix/ramful-mbc.err
  test/fix/ramless-mbc.err
  test/fix/rom-ram.err
  test/fix/sgb-licensee.err
  test/fix/sgb.err
  test/fix/title-color-trunc-rev.err
  test/fix/title-color-trunc.err
  test/fix/title-compat-trunc-rev.err
  test/fix/title-compat-trunc.err
  test/fix/title-gameid-trunc-rev.err
  test/fix/title-gameid-trunc.err
  test/fix/title-pad.err
  test/fix/title-trunc.err
  test/fix/title.err
  test/fix/verify-pad.err
  test/fix/verify-trash.err
  test/fix/verify.err
  test/fix/version.err
Labels: enhancement, rgbfix

#858 Allow REDEF for EQU constants
  include/asm/symbol.h
  src/asm/parser.y
  src/asm/rgbasm.5
  src/asm/symbol.c
  test/asm/def.asm
  test/asm/def.err
  test/asm/def.out
  test/asm/redef-equ.asm
  test/asm/redef-equ.err
  test/asm/redef-equ.out
  test/asm/reference-undefined-equs.asm
  test/asm/reference-undefined-equs.err
  test/asm/reference-undefined-equs.out
  test/asm/reference-undefined-sym.asm
  test/asm/reference-undefined-sym.out.bin
Labels: enhancement, rgbasm
