Repository gbdev/rgbds, pull requests merged in 2023-12, with the labels that each got.

#1259 Refactor how Makefile invokes Bison for reusability
  Makefile
  src/bison.sh
  src/check_bison_ver.sh
  src/link/main.cpp
Labels: rgblink, refactoring

#1264 Add SameBoy's BootROMs to the test suite
  test/.gitignore
  test/fetch-test-deps.sh
  test/run-tests.sh
Labels: tests

#1265 Add LADX disassembly to test suite
  test/.gitignore
  test/fetch-test-deps.sh
  test/run-tests.sh
Labels: tests

#1269 Use `RANGE` macro to abbreviate `begin`/`end` pairs
  include/helpers.hpp
  src/gfx/pal_packing.cpp
  src/gfx/pal_sorting.cpp
  src/gfx/pal_spec.cpp
  src/gfx/process.cpp
  src/gfx/proto_palette.cpp
  src/link/script.y
Labels: rgblink, rgbgfx, refactoring

#1272 Don't delete script.cpp after building
  Makefile
  include/link/script.hpp
  src/link/main.cpp
  src/link/script.y
Labels: rgblink, builds

#1273 Scramble banks from the end of the ROM
  src/link/assign.cpp
  test/asm/test.sh
  test/link/scramble-romx/a.asm
  test/link/scramble-romx/out.err
  test/link/test.sh
Labels: enhancement, rgblink

#1271 Linker scripts can align to offsets, and require valid alignments
  man/rgblink.5
  src/link/script.y
  test/link/section-attributes-mismatch.out
  test/link/section-attributes.asm
  test/link/section-attributes.link
Labels: enhancement, rgblink

#1279 Update the man pages' dates and history
  man/gbz80.7
  man/rgbasm.1
  man/rgbasm.5
  man/rgbds.5
  man/rgbds.7
  man/rgbfix.1
  man/rgbgfx.1
  man/rgblink.1
  man/rgblink.5
Labels: docs

#1275 Improve linker scripts a little
  man/rgblink.5
  src/link/script.y
Labels: bug, enhancement, rgblink

#1280 Build for macOS 10.14 and below
  .github/workflows/create-release-artifacts.yml
  .github/workflows/testing.yml
  Dockerfile
  Makefile
  include/hacks/__availability
Labels: bug, builds

#1284 Allow fewer tRNS entries than PLTE colors
  include/gfx/pal_sorting.hpp
  src/gfx/pal_sorting.cpp
  src/gfx/process.cpp
  test/gfx/rgbgfx_test.cpp
  test/gfx/trns_lt_plte.err
  test/gfx/trns_lt_plte.flags
  test/gfx/trns_lt_plte.png
Labels: bug, rgbgfx
