Repository gbdev/rgbds, pull requests merged in 2023-11, with the labels that each got.

#1198 Update the pret repos being tested
  test/fetch-test-deps.sh
  test/patches/pokecrystal.patch
Labels: tests

#1197 Correct documentation for `rgbgfx -r`
  man/rgbgfx.1
Labels: docs, rgbgfx

#1179 Consistent behavior with missing or incorrect arguments
  man/rgbasm.1
  man/rgbfix.1
  man/rgblink.1
  src/asm/main.c
  src/fix/main.c
  src/gfx/main.cpp
  src/link/main.c
  test/fix/test.sh
Labels: rgbasm, rgblink, rgbfix, rgbgfx

#1192 Allow rgbgfx to generate a palette from a spec, without an image
  include/gfx/process.hpp
  man/rgbgfx.1
  src/gfx/main.cpp
  src/gfx/process.cpp
Labels: enhancement, rgbgfx

#1184 Implement `INCHARMAP` function
  include/asm/charmap.h
  man/rgbasm.5
  src/asm/charmap.c
  src/asm/lexer.c
  src/asm/parser.y
  test/asm/incharmap.asm
  test/asm/incharmap.err
  test/asm/incharmap.out
Labels: enhancement, rgbasm

#1207 Update the ucity repo being tested
  test/fetch-test-deps.sh
Labels: tests

#1186 Sort symbols by address, then parentage, then index
  src/link/output.c
Labels: enhancement, rgblink

#1209 Actually use PNGCFLAGS to build rgbgfx
  Makefile
Labels: bug, rgbgfx

#1206 Implement `DS` for linker scripts
  man/rgblink.5
  src/link/script.c
  test/link/section-attributes.asm
  test/link/section-attributes.link
Labels: enhancement, rgblink

#1205 Implement SIZEOF and STARTOF for section types
  include/asm/rpn.h
  include/linkdefs.h
  man/rgbasm.5
  man/rgbds.5
  src/asm/parser.y
  src/asm/rpn.c
  src/link/patch.c
  test/link/sizeof-startof.asm
  test/link/sizeof-startof.out.bin
Labels: enhancement, rgbasm, rgbfix

#1212 Update ucity for testing
  test/fetch-test-deps.sh
Labels: tests

#1215 Remove deprecated RGBASM features
  include/asm/main.h
  man/rgbasm.1
  man/rgbasm.5
  src/asm/lexer.c
  src/asm/main.c
  src/asm/opt.c
  src/asm/parser.y
  src/asm/symbol.c
  test/asm/.gitignore
  test/asm/file-sym.asm
  test/asm/file-sym.err
  test/asm/file-sym.out
  test/asm/label-indent.asm
  test/asm/label-indent.err
  test/asm/label-indent.out
  test/asm/macro-syntax.asm
  test/asm/macro-syntax.err
  test/asm/macro-syntax.out
  test/asm/macro-syntax.simple.err
  test/link/all-instructions.asm
Labels: enhancement, rgbasm

#1216 `#!/bin/bash` -> `#!/usr/bin/env bash`
  .github/scripts/install.sh
  .github/scripts/install_deps.sh
  .github/scripts/mingw-w64-libpng-dev.sh
  Makefile
  contrib/checkdiff.bash
  contrib/gbdiff.bash
  test/fix/test.sh
Labels: tests, meta

#1211 Implement `ENDSECTION`
  include/asm/section.h
  man/rgbasm.5
  src/asm/charmap.c
  src/asm/fstack.c
  src/asm/lexer.c
  src/asm/parser.y
  src/asm/section.c
  src/gfx/main.cpp
  src/gfx/reverse.cpp
  test/asm/endsection.asm
  test/asm/endsection.err
  test/asm/endsection.out
Labels: enhancement, rgbasm

#1203 Output the map file summary at the top of the file
  src/gfx/main.cpp
  src/link/output.c
Labels: enhancement, rgblink

#1219 Reminder to update the Dockerfile version for a release
  RELEASE.rst
Labels: meta

#1210 Separate multiple instructions per line with `::`
  man/rgbasm.5
  src/asm/lexer.c
  src/asm/parser.y
  test/asm/anon-label-bad.err
  test/asm/macro-syntax.err
  test/asm/macro-syntax.simple.err
  test/asm/multiple-instructions.asm
  test/asm/multiple-instructions.err
  test/asm/multiple-instructions.out
  test/asm/multiple-instructions.out.bin
Labels: enhancement, rgbasm

#1218 Fix use of input slice without dedup active
  src/gfx/process.cpp
Labels: bug, rgbgfx

#1224 Fix RGBGFX `-r` with `-d 1`
  src/gfx/reverse.cpp
Labels: bug, rgbgfx

#1223 Download libpng source from GitHub, not SourceForge
  .github/scripts/get_win_deps.ps1
Labels: meta

#1200 Fix the rgbgfx color curve
  src/gfx/rgba.cpp
Labels: bug, rgbgfx

#1195 Make requested revisions to recent PRs
  man/rgbasm.1
  man/rgbasm.5
  src/fix/main.cpp
  src/link/object.cpp
Labels: bug, docs

#1222 Fix the FOR loop count and increment formulas
  src/asm/fstack.cpp
  test/asm/for-loop-count.asm
  test/asm/for-loop-count.err
  test/asm/for-loop-count.out
Labels: bug, rgbasm

#1122 Implement `#"raw strings"`
  man/rgbasm.5
  src/asm/lexer.cpp
  test/asm/raw-strings.asm
  test/asm/raw-strings.err
  test/asm/raw-strings.out
Labels: enhancement, rgbasm

#1227 AUTHORS and more copyright comments are redundant with CONTRIBUTORS.rst
  .dockerignore
  AUTHORS
  CMakeLists.txt
  CONTRIBUTORS.rst
  Makefile
  README.rst
  contrib/checkdiff.bash
  contrib/gbdiff.bash
  include/extern/getopt.hpp
  src/extern/getopt.cpp
  src/extern/utf8decoder.cpp
  src/opmath.cpp
Labels: docs, meta

#1221 Build a code coverage report with gcov and lcov
  .gitignore
  Makefile
  contrib/coverage.bash
Labels: tests, meta

#1233 Add exact dates for history
  README.rst
Labels: docs

#1230 Rename some RPN constants for consistency
  include/asm/rpn.hpp
  include/linkdefs.hpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/link/patch.cpp
Labels: refactoring

#1231 Use some more C++20 features
  src/fix/main.cpp
  src/gfx/pal_spec.cpp
  src/link/main.cpp
  src/link/output.cpp
Labels: refactoring

#1228 Use an iterator template for enum sequence loops
  include/gfx/main.hpp
  include/gfx/pal_packing.hpp
  include/gfx/pal_sorting.hpp
  include/itertools.hpp
  src/asm/warning.cpp
  src/link/assign.cpp
  src/link/main.cpp
  src/link/output.cpp
  src/link/script.cpp
Labels: refactoring

#1235 Switch to using `std::filesystem`
  include/file.hpp
  include/gfx/main.hpp
  src/gfx/main.cpp
  src/gfx/process.cpp
  src/gfx/reverse.cpp
Labels: rgbgfx, refactoring

#1242 Fix the hack for `File::c_str` to work
  include/file.hpp
  src/gfx/main.cpp
  src/gfx/process.cpp
  src/gfx/reverse.cpp
Labels: rgbgfx, refactoring

#1238 Fix spurious truncation warning
  man/rgbasm.1
  src/asm/rpn.cpp
  test/asm/warn-truncation.asm
  test/asm/warn-truncation.err
Labels: bug, rgbasm

#1244 Avoid building test support programs by default with CMake
  .github/workflows/testing.yml
  test/CMakeLists.txt
Labels: tests

#1240 Implement `rgbgfx -O`
  contrib/bash_compl/_rgbgfx.bash
  contrib/zsh_compl/_rgbgfx
  man/rgbgfx.1
  src/gfx/main.cpp
Labels: enhancement, rgbgfx

#1245 Rename the RGBGFX `--output-*` options to `--auto-*`
  contrib/bash_compl/_rgbgfx.bash
  contrib/zsh_compl/_rgbgfx
  man/rgbgfx.1
  src/gfx/main.cpp
Labels: enhancement, rgbgfx

#1246 Remove deprecated RGBGFX options
  contrib/zsh_compl/_rgbgfx
  src/gfx/main.cpp
Labels: enhancement, rgbgfx

#1181 Implement `ds align[alignment, offset]`
  include/asm/lexer.hpp
  include/asm/section.hpp
  man/rgbasm.5
  src/asm/parser.y
  src/asm/section.cpp
  test/asm/ds-align-min.asm
  test/asm/ds-align-min.err
  test/asm/ds-align-min.out
  test/asm/ds-align-min.out.bin
  test/asm/ds-align-offset.asm
  test/asm/ds-align-offset.err
  test/asm/ds-align-offset.out
  test/asm/ds-align-offset.out.bin
  test/asm/ds-align.asm
  test/asm/ds-align.err
  test/asm/ds-align.out
  test/asm/ds-align.out.bin
Labels: enhancement, rgbasm

#1252 Document pre-ASMotor history and add links
  README.rst
Labels: docs

#1253 Refactor alignment spec parsing
  include/asm/lexer.hpp
  src/asm/parser.y
Labels: rgbasm, refactoring

#1255 Allow negative alignment offsets
  src/asm/parser.y
  test/asm/align-large-ofs.err
  test/asm/align-offset.asm
  test/asm/align-offset.err
Labels: enhancement, rgbasm

#1256 Add more test coverage for RGBASM
  include/asm/charmap.hpp
  include/asm/section.hpp
  include/asm/symbol.hpp
  src/asm/charmap.cpp
  src/asm/fstack.cpp
  src/asm/section.cpp
  src/asm/symbol.cpp
  src/opmath.cpp
  test/asm/assert-fatal.asm
  test/asm/assert-fatal.err
  test/asm/assert@-no-sect.asm
  test/asm/builtin-overwrite.asm
  test/asm/builtin-overwrite.err
  test/asm/builtin-overwrite.out
  test/asm/charmap-inheritance.asm
  test/asm/charmap-inheritance.err
  test/asm/crlf.asm
  test/asm/def-scoped.asm
  test/asm/def-scoped.err
  test/asm/diff-marks.asm
  test/asm/diff-marks.err
  test/asm/div-mod.asm
  test/asm/fail.asm
  test/asm/fail.err
  test/asm/invalid-instructions.asm
  test/asm/invalid-instructions.err
  test/asm/invalid-numbers.asm
  test/asm/invalid-numbers.err
  test/asm/math.asm
  test/asm/modzero-instr.asm
  test/asm/modzero-instr.err
  test/asm/negative-exponent.asm
  test/asm/negative-exponent.err
  test/asm/purge-multiple.asm
  test/asm/redef-equ.asm
  test/asm/redef-equ.err
  test/asm/redef-equs.asm
  test/asm/redef-equs.err
  test/asm/shift.asm
  test/asm/shift.err
  test/asm/shift.out
  test/asm/shift.out.bin
  test/asm/strfmt.asm
  test/asm/strfmt.err
  test/asm/strfmt.out
  test/asm/string-formatting.asm
  test/asm/string-formatting.out
  test/asm/trigonometry.asm
  test/asm/utc-time.asm
  test/link/all-instructions.asm
  test/link/all-instructions.out.bin
Labels: bug, tests, rgbasm
