Repository gbdev/rgbds, pull requests merged in 2024-09, with the labels that each got.

#1487 Traverse the charmap trie to reconstruct mappings instead of saving them
  src/asm/charmap.cpp
Labels: rgbasm, refactoring, optimization

#1491 Improve string/interpolation formatting
  include/asm/format.hpp
  man/rgbasm.5
  src/asm/format.cpp
  test/asm/fixed-point-precision.asm
  test/asm/fixed-point-precision.err
  test/asm/fixed-point-precision.out
  test/asm/fixed-point-specific.asm
  test/asm/invalid-format.asm
  test/asm/invalid-format.err
  test/asm/invalid-format.out
  test/asm/string-formatting.asm
  test/asm/string-formatting.err
  test/asm/string-formatting.out
Labels: enhancement, rgbasm

#1493 Allow dollar signs in identifiers
  man/rgbasm.5
  src/asm/lexer.cpp
  test/asm/symbol-names.asm
Labels: enhancement, rgbasm

#1464 Implement `--input-tileset`
  contrib/bash_compl/_rgbgfx.bash
  contrib/zsh_compl/_rgbgfx
  include/gfx/main.hpp
  man/rgbgfx.1
  src/gfx/main.cpp
  src/gfx/process.cpp
  test/gfx/input_tileset.flags
  test/gfx/input_tileset.in.2bpp
  test/gfx/input_tileset.out.2bpp
  test/gfx/input_tileset.png
  test/gfx/input_tileset_deduped.err
  test/gfx/input_tileset_deduped.flags
  test/gfx/input_tileset_deduped.in.2bpp
  test/gfx/input_tileset_deduped.png
  test/gfx/input_tileset_extra.err
  test/gfx/input_tileset_extra.flags
  test/gfx/input_tileset_extra.in.2bpp
  test/gfx/input_tileset_extra.png
Labels: enhancement, rgbgfx

#1496 RGBLINK lists local symbols when encountering an unknown symbol reference
  include/link/symbol.hpp
  src/link/object.cpp
  src/link/patch.cpp
  src/link/sdas_obj.cpp
  src/link/symbol.cpp
  test/link/symbols/good/a.asm
  test/link/symbols/good/b.asm
  test/link/symbols/good/out.err
  test/link/symbols/good/ref.out.bin
  test/link/symbols/good/ref.out.sym
  test/link/symbols/unknown/a.asm
  test/link/symbols/unknown/b.asm
  test/link/symbols/unknown/c.asm
  test/link/symbols/unknown/d.asm
  test/link/symbols/unknown/e.asm
  test/link/symbols/unknown/out.err
  test/link/test.sh
Labels: enhancement, rgblink

#1481 Implement `INCLUDE_ONCE` directive
  include/asm/fstack.hpp
  man/rgbasm.5
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/parser.y
  test/asm/include-once.asm
  test/asm/include-once.inc
  test/asm/test.sh
Labels: enhancement, rgbasm

#1494 Report locations for RGBLINK errors with conflicting objects
  include/link/section.hpp
  include/link/symbol.hpp
  man/rgbds.5
  src/asm/output.cpp
  src/asm/section.cpp
  src/link/object.cpp
  src/link/sdas_obj.cpp
  src/link/section.cpp
  src/link/symbol.cpp
  test/link/fragment-align/base-bad/out.err
  test/link/fragment-align/org-bad/out.err
  test/link/fragment-align/org-rev-bad/out.err
  test/link/section-normal/same-name/a.asm
  test/link/section-normal/same-name/b.asm
  test/link/section-normal/same-name/out.err
  test/link/section-union/align-conflict.out
  test/link/section-union/align-ofs-conflict.out
  test/link/section-union/bad-types.out
  test/link/section-union/bank-conflict.out
  test/link/section-union/different-ofs.out
  test/link/section-union/org-conflict.out
  test/link/section-union/same-export/out.err
  test/link/symbols/conflict/a.asm
  test/link/symbols/conflict/b.asm
  test/link/symbols/conflict/out.err
  test/link/test.sh
Labels: enhancement, rgbasm, rgblink

#1501 More accurate error messages for "undefined" built-ins
  src/asm/symbol.cpp
  test/asm/builtin-reserved.asm
  test/asm/builtin-reserved.err
Labels: enhancement, rgbasm

#1499 Implement `.` string constant for the current label scope
  include/asm/symbol.hpp
  man/rgbasm.5
  src/asm/lexer.cpp
  src/asm/parser.y
  src/asm/symbol.cpp
  test/asm/builtin-reserved.asm
  test/asm/builtin-reserved.err
  test/asm/label-scope.asm
  test/asm/label-scope.err
  test/asm/label-scope.out
  test/asm/period.asm
  test/asm/period.err
  test/asm/undefined-builtins.asm
  test/asm/undefined-builtins.err
  test/asm/undefined-builtins.out
Labels: enhancement, rgbasm

#1505 No need for `.c_str()` with `keywordDict` lookups
  src/asm/lexer.cpp
Labels: rgbasm, refactoring

#1504 Track local label scope, string equated as `..`
  include/asm/symbol.hpp
  man/rgbasm.5
  src/asm/lexer.cpp
  src/asm/section.cpp
  src/asm/symbol.cpp
  test/asm/label-scope.asm
  test/asm/label-scope.err
  test/asm/label-scope.out
  test/asm/period.asm
  test/asm/period.err
  test/asm/undefined-builtins.asm
  test/asm/undefined-builtins.err
  test/asm/undefined-builtins.out
Labels: enhancement, rgbasm

#1510 Refactor some workflows for consistency
  .github/workflows/build-container.yml
  .github/workflows/checkdiff.yml
  .github/workflows/create-release-artifacts.yml
  .github/workflows/create-release-docs.yml
  .github/workflows/testing.yml
  .github/workflows/update-master-docs.yml
Labels: builds

#1516 Add test to demonstrate lack of expansions in `skipIfBlock`
  test/asm/skip-expansions.asm
  test/asm/skip-expansions.err
  test/asm/skip-expansions.out
Labels: tests, rgbasm

#1515 Don't treat labels and macros differently in column 1
  man/rgbasm.5
  src/asm/lexer.cpp
  src/asm/parser.y
  test/asm/lexer-hack.asm
  test/asm/lexer-hack.err
  test/asm/lexer-hack.out
  test/asm/syntax-error-after-syntax-error.asm
  test/asm/syntax-error-after-syntax-error.err
  test/asm/syntax-error-after-syntax-error.out
Labels: enhancement, rgbasm

#1517 Refer to "end of line", not "newline"
  src/asm/parser.y
  src/link/script.y
  test/asm/charmap-empty.err
  test/asm/code-after-endm-endr-endc.err
  test/asm/invalid-opt.err
  test/asm/syntax-error-after-syntax-error.err
  test/asm/syntax-error-eof-newline.err
  test/link/script-syntax-error.out
Labels: tests, rgbasm

#1518 Simplify some C++ abstractions
  include/defaultinitvec.hpp
  include/gfx/main.hpp
  include/gfx/pal_packing.hpp
  include/gfx/pal_sorting.hpp
  include/gfx/rgba.hpp
  include/itertools.hpp
  src/gfx/pal_packing.cpp
  src/gfx/pal_sorting.cpp
  src/gfx/process.cpp
  src/gfx/reverse.cpp
  test/gfx/rgbgfx_test.cpp
Labels: refactoring

#1520 Use `setmode` instead of `fdopen`
  src/asm/output.cpp
  src/fix/main.cpp
  src/link/object.cpp
  src/link/output.cpp
Labels: refactoring

#1524 Move definition of `_POSIX_C_SOURCE` to include/platform.hpp
  CMakeLists.txt
  Makefile
  include/platform.hpp
Labels: builds

#1528 `-Wall` enables `-Wcharmap-redef`, and document `-Wnested-comment`
  man/rgbasm.1
  src/asm/warning.cpp
  test/asm/multiple-charmaps.err
  test/asm/pushc-without-switch.asm
Labels: bug, docs, rgbasm
