Repository gbdev/rgbds, pull requests merged in 2024-07, with the labels that each got.

#1416 Fix bison.sh for patch-less bison versions
  src/bison.sh
Labels: builds

#1426 Fix use-after-free when keeping pointers to args from at-files
  src/gfx/main.cpp
  test/gfx/at-file-ref.err
  test/gfx/at-file-ref.flags
  test/gfx/at-file-ref.png
Labels: bug, rgbgfx

#1421 Push and modify stacks in one step (for PUSHS, PUSHO, and PUSHC)
  man/rgbasm.5
  src/asm/parser.y
  test/asm/invalid-opt.asm
  test/asm/invalid-opt.err
  test/asm/multiple-charmaps.asm
  test/asm/multiple-charmaps.err
  test/asm/multiple-charmaps.out
  test/asm/opt.asm
  test/asm/opt.out.bin
Labels: enhancement, rgbasm

#1423 Improve the error messages for interpolating undefined or invalid symbols
  src/asm/lexer.cpp
  test/asm/interpolation.asm
  test/asm/interpolation.err
  test/asm/interpolation.out
Labels: enhancement, rgbasm

#1422 Implement `EXPORT DEF` to define and export symbols
  man/rgbasm.5
  src/asm/parser.y
  test/asm/anon-label-bad.err
  test/asm/export.asm
  test/asm/export.err
Labels: enhancement, rgbasm

#1431 Some refactoring and reformatting
  include/link/main.hpp
  src/asm/format.cpp
  src/asm/main.cpp
  src/asm/output.cpp
  src/gfx/main.cpp
  src/link/main.cpp
Labels: refactoring
