Repository gbdev/rgbds, pull requests merged in 2024-02, with the labels that each got.

#1298 Phrase error messages as "Failed to", not "Could not" or "Couldn't"
  src/asm/main.cpp
  src/asm/symbol.cpp
  src/gfx/pal_spec.cpp
  src/gfx/process.cpp
  src/gfx/reverse.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/patch.cpp
  src/link/script.y
  src/link/sdas_obj.cpp
  test/gfx/bad_manual_pals.err
  test/link/cascading-errors-fatal-assert.out
Labels: rgbasm, rgblink, rgbgfx

#1296 Explain to remove the deprecated rgbasm flags
  src/asm/main.cpp
  src/asm/opt.cpp
  src/asm/parser.y
Labels: enhancement, rgbasm

#1297 Report "<stdin>" or "<stdout>" when using "-" as a filename placeholder
  include/asm/output.hpp
  include/link/main.hpp
  src/asm/main.cpp
  src/asm/output.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/output.cpp
Labels: bug, enhancement, rgbasm, rgblink

#1303 Make sure to detect Git info from *our* Git repo
  CMakeLists.txt
  Makefile
Labels: bug, builds

#1308 Fix behavior of non-ASCII bytes with `INCHARMAP`
  src/asm/charmap.cpp
  test/asm/charmap-unicode.asm
Labels: bug, rgbasm

#1305 No more anonymous structs (not standard C++)
  include/asm/symbol.hpp
  include/link/main.hpp
  include/platform.hpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/symbol.cpp
  src/link/main.cpp
  src/link/object.cpp
Labels: rgbasm, rgblink, refactoring

#1310 Simplify `fstk_FindFile` usage
  include/asm/fstack.hpp
  src/asm/fstack.cpp
  src/asm/section.cpp
Labels: rgbasm, refactoring

#1307 No more flexible array members (not standard C++)
  include/asm/fstack.hpp
  include/asm/macro.hpp
  include/asm/symbol.hpp
  include/link/main.hpp
  src/asm/charmap.cpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/macro.cpp
  src/asm/output.cpp
  src/asm/parser.y
  src/link/sdas_obj.cpp
  test/asm/unique-id.asm
Labels: rgbasm, refactoring

#1309 Build with pedantically standard C++
  CMakeLists.txt
  Makefile
  include/asm/lexer.hpp
  include/platform.hpp
  src/asm/lexer.cpp
  src/asm/warning.cpp
  src/link/main.cpp
  src/link/output.cpp
  src/link/patch.cpp
  src/linkdefs.cpp
Labels: builds

#1317 Remove `#include <stdbool.h>`
  include/asm/charmap.hpp
  include/asm/format.hpp
  include/asm/fstack.hpp
  include/asm/lexer.hpp
  include/asm/macro.hpp
  include/asm/main.hpp
  include/asm/opt.hpp
  include/asm/rpn.hpp
  include/asm/section.hpp
  include/asm/symbol.hpp
  include/hashmap.hpp
  include/link/main.hpp
  include/link/patch.hpp
  include/link/section.hpp
  include/linkdefs.hpp
  src/asm/charmap.cpp
  src/asm/format.cpp
  src/asm/lexer.cpp
  src/asm/macro.cpp
  src/asm/opt.cpp
  src/asm/parser.y
  src/asm/section.cpp
  src/fix/main.cpp
  src/hashmap.cpp
  src/link/assign.cpp
  src/link/main.cpp
  src/link/section.cpp
  src/link/symbol.cpp
Labels: refactoring

#1318 Fix fstack traces for macro nodes
  src/asm/fstack.cpp
  test/asm/rept-macro-fstack-trace.asm
  test/asm/rept-macro-fstack-trace.err
Labels: bug, rgbasm

#1320 Remove now-unnecessary `struct` keyword
  include/asm/format.hpp
  include/asm/fstack.hpp
  include/asm/lexer.hpp
  include/asm/macro.hpp
  include/asm/output.hpp
  include/asm/rpn.hpp
  include/asm/section.hpp
  include/asm/symbol.hpp
  include/extern/getopt.hpp
  include/link/main.hpp
  include/link/output.hpp
  include/link/patch.hpp
  include/link/sdas_obj.hpp
  include/link/section.hpp
  include/link/symbol.hpp
  src/asm/charmap.cpp
  src/asm/format.cpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/macro.cpp
  src/asm/main.cpp
  src/asm/opt.cpp
  src/asm/output.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/asm/section.cpp
  src/asm/symbol.cpp
  src/extern/getopt.cpp
  src/fix/main.cpp
  src/gfx/main.cpp
  src/link/assign.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/output.cpp
  src/link/patch.cpp
  src/link/sdas_obj.cpp
  src/link/section.cpp
  src/link/symbol.cpp
  src/linkdefs.cpp
  test/gfx/randtilegen.cpp
Labels: refactoring

#1321 Replace `NULL` with `nullptr`
  include/asm/fstack.hpp
  include/asm/lexer.hpp
  include/link/patch.hpp
  include/link/section.hpp
  include/link/symbol.hpp
  src/asm/charmap.cpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/macro.cpp
  src/asm/main.cpp
  src/asm/output.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/asm/section.cpp
  src/asm/symbol.cpp
  src/asm/warning.cpp
  src/fix/main.cpp
  src/gfx/main.cpp
  src/link/assign.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/output.cpp
  src/link/script.y
  src/link/sdas_obj.cpp
  src/link/section.cpp
  src/link/symbol.cpp
  test/gfx/randtilegen.cpp
Labels: refactoring
