Repository gbdev/rgbds, pull requests merged in 2024-03, with the labels that each got.

#1323 Use `std::deque` for free space
  src/link/assign.cpp
  src/link/main.cpp
Labels: refactoring

#1325 Use RAII `std::string` and `std::vector` in randtilegen
  test/gfx/randtilegen.cpp
Labels: tests, refactoring

#1326 Use `std::string_view` for macro bodies
  include/asm/fstack.hpp
  include/asm/lexer.hpp
  include/asm/symbol.hpp
  include/platform.hpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/symbol.cpp
Labels: rgbasm, refactoring

#1301 Implement `-c #none`
  include/gfx/main.hpp
  man/rgbgfx.1
  src/gfx/main.cpp
  src/gfx/pal_spec.cpp
  src/gfx/process.cpp
  src/gfx/reverse.cpp
  test/gfx/none_comma_ommission.err
  test/gfx/none_comma_ommission.flags
  test/gfx/none_comma_ommission.png
  test/gfx/none_round_trip.2bpp
  test/gfx/rgbgfx_test.cpp
  test/gfx/test.sh
Labels: enhancement, rgbgfx

#1328 Use `std::variant` for lexer mmap/buffer state
  include/asm/lexer.hpp
  src/asm/lexer.cpp
Labels: rgbasm, refactoring

#1329 Use uncommented sizes for pointer-to-array arguments
  include/asm/symbol.hpp
  src/asm/symbol.cpp
  test/gfx/randtilegen.cpp
Labels: refactoring

#1330 Use `std::variant` for symbol values
  include/link/symbol.hpp
  src/link/object.cpp
  src/link/output.cpp
  src/link/patch.cpp
  src/link/sdas_obj.cpp
  src/link/symbol.cpp
Labels: rgblink, refactoring

#1331 Use `std::variant` for symbol values
  include/asm/symbol.hpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/output.cpp
  src/asm/symbol.cpp
Labels: rgbasm, refactoring

#1333 Adapt the RGBASM parser to C++
  Makefile
  include/asm/lexer.hpp
  src/asm/.gitignore
  src/asm/lexer.cpp
  src/asm/main.cpp
  src/asm/parser.y
Labels: refactoring

#1338 Remove now-unnecessary `enum` keyword
  include/asm/format.hpp
  include/asm/fstack.hpp
  include/asm/lexer.hpp
  include/asm/output.hpp
  include/asm/rpn.hpp
  include/asm/section.hpp
  include/asm/symbol.hpp
  include/asm/warning.hpp
  include/link/main.hpp
  include/link/section.hpp
  include/link/symbol.hpp
  include/linkdefs.hpp
  src/asm/lexer.cpp
  src/asm/opt.cpp
  src/asm/output.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/asm/section.cpp
  src/asm/warning.cpp
  src/fix/main.cpp
  src/link/assign.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/output.cpp
  src/link/patch.cpp
  src/link/sdas_obj.cpp
  src/link/section.cpp
Labels: refactoring

#1337 Use `std::unique_ptr` for rgblink sections
  include/link/section.hpp
  src/link/assign.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/output.cpp
  src/link/patch.cpp
  src/link/script.y
  src/link/sdas_obj.cpp
  src/link/section.cpp
Labels: rgblink, refactoring

#1336 Use automatic allocation and `std::move` for RPN bytes
  include/asm/rpn.hpp
  src/asm/output.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
Labels: rgbasm, refactoring

#1343 Make enum patterns more explicit
  src/asm/parser.y
Labels: rgbasm, refactoring

#1342 Reduce the header declarations
  include/extern/utf8decoder.hpp
  include/gfx/rgba.hpp
  include/itertools.hpp
  include/link/assign.hpp
  include/link/main.hpp
  include/link/object.hpp
  include/link/output.hpp
  include/link/patch.hpp
  include/link/sdas_obj.hpp
  include/link/section.hpp
  include/link/symbol.hpp
  include/platform.hpp
  src/asm/charmap.cpp
  src/asm/fixpoint.cpp
  src/asm/format.cpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/macro.cpp
  src/asm/main.cpp
  src/asm/opt.cpp
  src/asm/output.cpp
  src/asm/rpn.cpp
  src/asm/section.cpp
  src/asm/symbol.cpp
  src/extern/utf8decoder.cpp
  src/gfx/main.cpp
  src/gfx/pal_packing.cpp
  src/gfx/pal_sorting.cpp
  src/gfx/pal_spec.cpp
  src/gfx/process.cpp
  src/gfx/proto_palette.cpp
  src/gfx/reverse.cpp
  src/link/main.cpp
  src/link/output.cpp
  src/link/patch.cpp
  src/link/script.y
  src/link/sdas_obj.cpp
  src/link/section.cpp
  src/link/symbol.cpp
Labels: refactoring

#1347 Consistently format type qualifiers like `const` on the right
  .clang-format
  include/asm/fstack.hpp
  include/asm/output.hpp
  include/asm/rpn.hpp
  include/extern/getopt.hpp
  include/platform.hpp
  src/asm/fstack.cpp
  src/asm/main.cpp
  src/asm/opt.cpp
  src/asm/output.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/asm/symbol.cpp
  src/asm/warning.cpp
  src/error.cpp
  src/extern/getopt.cpp
  src/fix/main.cpp
  src/gfx/main.cpp
  src/gfx/pal_spec.cpp
  src/gfx/reverse.cpp
  src/link/main.cpp
  src/link/script.y
Labels: refactoring

#1353 Refactor link/test.sh to avoid repeating test names
  test/link/test.sh
Labels: tests, rgblink

#1349 Add test cases for SECTION UNION defining multiple identical labels
  .github/workflows/testing.yml
  Makefile
  test/CMakeLists.txt
  test/link/.gitignore
  test/link/section-union/same-export/a.asm
  test/link/section-union/same-export/b.asm
  test/link/section-union/same-export/out.err
  test/link/section-union/same-label/a.asm
  test/link/section-union/same-label/b.asm
  test/link/section-union/same-label/out.err
  test/link/test.sh
  test/link/unmangle.cpp
Labels: tests, rgblink

#1341 Allow multiple identical exported numeric constants
  src/link/symbol.cpp
  test/link/same-consts/a.asm
  test/link/same-consts/b.asm
  test/link/same-consts/out.err
  test/link/test.sh
Labels: enhancement, rgblink

#1345 Strip release binaries built with `make`
  .github/workflows/create-release-artifacts.yml
Labels: builds

#1354 Move a SECTION FRAGMENT test to the test/link/section-fragment folder
  test/link/section-fragment/good/a.asm
  test/link/section-fragment/good/b.asm
  test/link/section-fragment/good/ref.out.bin
  test/link/section-union/same-label/a.asm
  test/link/section-union/same-label/b.asm
  test/link/section-union/same-label/ref.out.bin
  test/link/test.sh
Labels: tests, rgblink

#1355 Sort .sym files in ascending order, and test for it
  src/link/output.cpp
  test/link/symbols/a.asm
  test/link/symbols/b.asm
  test/link/symbols/out.err
  test/link/symbols/ref.out.bin
  test/link/symbols/ref.out.sym
  test/link/test.sh
Labels: bug, tests, rgblink

#1357 Use a `std::unordered_map` for looking up sections by name
  include/asm/section.hpp
  src/asm/output.cpp
  src/asm/section.cpp
Labels: rgbasm, optimization

#1361 Fix CI builds for Ubuntu 22.04
  .github/workflows/testing.yml
Labels: bug, tests, builds

#1360 Use `std::string` for string-formatted values
  include/asm/format.hpp
  src/asm/format.cpp
  src/asm/lexer.cpp
  src/asm/parser.y
  test/asm/format-truncation.out
Labels: enhancement, rgbasm, refactoring

#1362 Built-in symbols are "<builtin>", not "<command-line>"
  src/asm/fstack.cpp
  src/asm/output.cpp
  src/asm/symbol.cpp
  test/asm/builtin-overwrite.err
  test/asm/rs-overwrite.asm
  test/asm/rs-overwrite.err
  test/asm/rs-overwrite.out
Labels: bug, rgbasm, refactoring

#1368 Remove workaround for GitHub Actions issue
  .github/workflows/testing.yml
Labels: tests, builds

#1367 Use `std::get_if` instead of `std::visit`
  include/file.hpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/parser.y
  src/asm/symbol.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/patch.cpp
  src/link/sdas_obj.cpp
  src/link/symbol.cpp
Labels: rgbasm, rgblink, optimization

#1370 Fix some header `#include`s with `clangd` LSP
  include/asm/fstack.hpp
  include/asm/lexer.hpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/output.cpp
  src/asm/section.cpp
  src/asm/symbol.cpp
  src/asm/warning.cpp
Labels: rgbasm, refactoring

#1366 Only restore parent context's `\@` value if it had one defined
  include/asm/fstack.hpp
  src/asm/fstack.cpp
  test/asm/unique-id-include.asm
  test/asm/unique-id-include.inc
  test/asm/unique-id-include.out
  test/asm/unique-id-nested.asm
  test/asm/unique-id-nested.out
Labels: bug, rgbasm

#1372 Use methods for RPN `Expression`
  include/asm/rpn.hpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/link/sdas_obj.cpp
Labels: rgbasm, refactoring

#1371 Use `std::shared_ptr` for fstack nodes
  include/asm/fstack.hpp
  include/asm/output.hpp
  include/asm/section.hpp
  include/asm/symbol.hpp
  src/asm/fstack.cpp
  src/asm/output.cpp
  src/asm/rpn.cpp
  src/asm/symbol.cpp
Labels: rgbasm, refactoring

#1373 Remove .simple.err files, since we require Bison 3.0
  test/asm/anon-label-bad.simple.err
  test/asm/block-comment-termination-error.simple.err
  test/asm/def.simple.err
  test/asm/error-recovery.simple.err
  test/asm/expand-empty-string.simple.err
  test/asm/label-macro-arg.simple.err
  test/asm/macro-syntax.simple.err
  test/asm/nested-macrodef.simple.err
  test/asm/period.simple.err
  test/asm/syntax-error-after-syntax-error.simple.err
  test/asm/syntax-error-eof-newline.simple.err
  test/asm/syntax-error.simple.err
  test/asm/test.sh
Labels: tests, rgbasm

#1377 Update test project commits
  test/fetch-test-deps.sh
Labels: tests

#1380 Use content-specific destructors for lexer state
  include/asm/lexer.hpp
  src/asm/lexer.cpp
  src/asm/parser.y
Labels: rgbasm, refactoring

#1379 Use a `DEFER` macro to close files and restore lexer state with RAII
  include/helpers.hpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/output.cpp
  src/asm/section.cpp
  src/fix/main.cpp
  src/gfx/process.cpp
  src/link/assign.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/output.cpp
  src/link/script.y
  src/link/sdas_obj.cpp
Labels: rgbasm, rgblink, refactoring

#1384 Verify ROM hashes for all CI test projects
  CONTRIBUTING.md
  test/patches/libbet.patch
  test/patches/ucity.patch
  test/run-tests.sh
Labels: tests

#1385 Make test built of 'libbet' reproducible with old Pillow versions
  contrib/coverage.bash
  test/patches/libbet.patch
Labels: tests

#1386 Add more RGBLINK tests
  test/link/invalid-bank-t.out
  test/link/invalid-bank.asm
  test/link/operators.asm
  test/link/operators.out
  test/link/operators.out.bin
  test/link/overlay/a.asm
  test/link/overlay/out.gb
  test/link/scramble-romx/a.asm
  test/link/test.sh
Labels: tests, rgblink

#1388 Fix two bugs with RGBASM fixed-point math
  src/asm/fixpoint.cpp
  src/asm/format.cpp
  test/asm/format-extremes.asm
  test/asm/format-extremes.out
  test/asm/math.asm
Labels: bug, rgbasm
