Repository gbdev/rgbds, pull requests merged in 2024-11, with the labels that each got.

#1557 Document the RGBGFX `-X` and `-Y` options
  man/rgbgfx.1
Labels: docs, rgbgfx

#1555 Add `reverse_1bit` RGBGFX test
  src/gfx/process.cpp
  test/gfx/reverse_1bit.1bpp
  test/gfx/reverse_1bit.attrmap
  test/gfx/reverse_1bit.flags
  test/gfx/reverse_1bit.tilemap
Labels: bug, tests, rgbgfx

#1563 Implement `-Wunmatched-directive`
  contrib/bash_compl/_rgbasm.bash
  contrib/zsh_compl/_rgbasm
  include/asm/charmap.hpp
  include/asm/opt.hpp
  include/asm/section.hpp
  include/asm/warning.hpp
  man/rgbasm.1
  src/asm/charmap.cpp
  src/asm/main.cpp
  src/asm/opt.cpp
  src/asm/section.cpp
  src/asm/warning.cpp
  test/asm/pushs.asm
  test/asm/unmatched-directive.asm
  test/asm/unmatched-directive.err
Labels: enhancement, rgbasm

#1564 Explain the DAA instruction algorithm
  man/gbz80.7
Labels: docs, rgbasm

#1565 Remove the use of floating-point for palette packing
  src/gfx/pal_packing.cpp
Labels: bug, rgbgfx
