Repository gbdev/rgbds, pull requests merged in 2024-10, with the labels that each got.

#1526 Refactoring and enhancements to RGBASM warnings
  include/asm/warning.hpp
  man/rgbasm.1
  src/asm/main.cpp
  src/asm/opt.cpp
  src/asm/warning.cpp
Labels: enhancement, rgbasm

#1533 Implement `0x/0o/0b` number prefixes
  man/rgbasm.5
  src/asm/lexer.cpp
  test/asm/number-prefixes.asm
Labels: enhancement, rgbasm

#1542 Fix nested undefined interpolation segfault
  src/asm/lexer.cpp
  test/asm/nested-bad-interpolation.asm
  test/asm/nested-bad-interpolation.err
Labels: bug, rgbasm

#1539 Make tests work with CTest
  .github/workflows/testing.yml
  .gitignore
  CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
  test/CTestCustom.cmake.in
Labels: tests, meta, builds

#1544 Update some RGBLINK error messages
  src/link/object.cpp
  src/link/patch.cpp
  test/link/ldh-bad.asm
  test/link/ldh-bad.out
  test/link/rst-bad.out
Labels: enhancement, rgblink

#1538 Make `ENDL` optional like `ENDSECTION`
  contrib/bash_compl/_rgbasm.bash
  contrib/zsh_compl/_rgbasm
  include/asm/section.hpp
  include/asm/warning.hpp
  man/rgbasm.1
  man/rgbasm.5
  src/asm/main.cpp
  src/asm/parser.y
  src/asm/section.cpp
  src/asm/warning.cpp
  test/asm/endsection-in-load.err
  test/asm/load-endings.asm
  test/asm/load-endings.err
  test/asm/load-endings.out.bin
  test/asm/load-in-load.asm
  test/asm/load-in-load.err
  test/asm/nested-bad-interpolation.asm
  test/asm/section-in-load.asm
  test/asm/section-in-load.err
  test/asm/unterminated-load.asm
  test/asm/unterminated-load.err
Labels: enhancement, rgbasm

#1536 `LOAD FRAGMENT` is not allowed
  man/rgbasm.5
Labels: bug, docs, rgbasm

#1546 Fix detection of tiles with too many colors
  include/gfx/proto_palette.hpp
  src/gfx/process.cpp
  src/gfx/proto_palette.cpp
Labels: bug, rgbgfx

#1547 Clean up some man pages
  man/gbz80.7
  man/rgbasm.5
  man/rgbds.5
Labels: docs

#1549 Errors may occur at the first token of a line
  src/asm/parser.y
  test/asm/macro-syntax.err
  test/asm/skip-expansions.asm
  test/asm/skip-expansions.err
  test/asm/skip-expansions.out
Labels: bug, rgbasm

#1551 Escape characters in section names in map files
  src/link/output.cpp
  test/link/map-file/a.asm
  test/link/map-file/ref.out.map
Labels: enhancement, rgblink

#1552 Allow `LOAD FRAGMENT`
  man/rgbasm.5
  src/asm/section.cpp
  test/asm/load-fragment.asm
  test/asm/load-fragment.err
  test/asm/load-fragment.out.bin
  test/link/load-fragment-jr.asm
  test/link/load-fragment-jr.out
  test/link/load-fragment-jr.out.bin
  test/link/load-fragment/base/a.asm
  test/link/load-fragment/base/ref.out.bin
  test/link/load-fragment/base/ref.out.sym
  test/link/load-fragment/multiple-objects/a.asm
  test/link/load-fragment/multiple-objects/b.asm
  test/link/load-fragment/multiple-objects/ref.out.bin
  test/link/load-fragment/section-fragment/a.asm
  test/link/load-fragment/section-fragment/b.asm
  test/link/load-fragment/section-fragment/c.asm
  test/link/load-fragment/section-fragment/ref.out.bin
  test/link/load-fragment/section-fragment/ref.out.map
  test/link/load-fragment/section-fragment/ref.out.sym
  test/link/section-fragment/jr-offset-load/a.asm
  test/link/section-fragment/jr-offset-load/b.asm
  test/link/section-fragment/jr-offset-load/ref.out.bin
  test/link/test.sh
Labels: enhancement, rgbasm, rgblink

#1553 Add more RGBGFX test coverage
  src/gfx/main.cpp
  test/gfx/empty_lines.hex
  test/gfx/full_aco.aco
  test/gfx/full_aco.flags
  test/gfx/full_aco.out.2bpp
  test/gfx/full_aco.out.attrmap
  test/gfx/full_aco.out.pal
  test/gfx/full_aco.out.tilemap
  test/gfx/full_aco.png
  test/gfx/full_act.act
  test/gfx/full_act.flags
  test/gfx/full_act.out.2bpp
  test/gfx/full_act.out.attrmap
  test/gfx/full_act.out.pal
  test/gfx/full_act.out.tilemap
  test/gfx/full_act.png
  test/gfx/full_gbc.flags
  test/gfx/full_gbc.out.2bpp
  test/gfx/full_gbc.out.attrmap
  test/gfx/full_gbc.out.pal
  test/gfx/full_gbc.out.tilemap
  test/gfx/full_gbc.pal
  test/gfx/full_gbc.png
  test/gfx/full_psp.flags
  test/gfx/full_psp.out.2bpp
  test/gfx/full_psp.out.attrmap
  test/gfx/full_psp.out.pal
  test/gfx/full_psp.out.tilemap
  test/gfx/full_psp.pal
  test/gfx/full_psp.png
  test/gfx/mirror_x.flags
  test/gfx/mirror_x.out.2bpp
  test/gfx/mirror_x.out.attrmap
  test/gfx/mirror_x.out.tilemap
  test/gfx/mirror_x.png
  test/gfx/mirror_xy.flags
  test/gfx/mirror_xy.out.2bpp
  test/gfx/mirror_xy.out.attrmap
  test/gfx/mirror_xy.out.tilemap
  test/gfx/mirror_xy.png
  test/gfx/mirror_y.flags
  test/gfx/mirror_y.out.2bpp
  test/gfx/mirror_y.out.attrmap
  test/gfx/mirror_y.out.tilemap
  test/gfx/mirror_y.png
  test/gfx/reverse_curve.2bpp
  test/gfx/reverse_curve.attrmap
  test/gfx/reverse_curve.flags
  test/gfx/reverse_curve.pal
  test/gfx/reverse_curve.tilemap
  test/gfx/test.sh
Labels: tests, rgbgfx
