Repository gbdev/rgbds, pull requests merged in 2024-08, with the labels that each got.

#1437 RGBGFX `-r 0` infers a width
  include/gfx/main.hpp
  man/rgbgfx.1
  src/gfx/main.cpp
  src/gfx/reverse.cpp
Labels: enhancement, rgbgfx

#1429 Implement multi-value charmaps
  include/asm/charmap.hpp
  include/asm/rpn.hpp
  include/asm/section.hpp
  include/util.hpp
  man/rgbasm.5
  src/asm/charmap.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/asm/section.cpp
  src/util.cpp
  test/asm/db-dw-dl-string.err
  test/asm/multiple-charmaps.err
  test/asm/multivalue-charmap.asm
  test/asm/multivalue-charmap.err
  test/asm/multivalue-charmap.out.bin
  test/asm/warn-numeric-string.err
Labels: enhancement, rgbasm

#1440 Update test deps
  test/fetch-test-deps.sh
  test/patches/LADX-Disassembly.patch
Labels: tests

#1441 Remove redundant "unknown option" error messages
  src/asm/main.cpp
  src/fix/main.cpp
  src/gfx/main.cpp
  src/link/main.cpp
Labels: rgbasm, rgblink, rgbfix, rgbgfx

#1438 Deprecate treating multi-unit strings as numbers
  src/asm/parser.y
  src/asm/warning.cpp
  test/asm/db-dw-dl-string.err
  test/asm/empty-strings.err
  test/asm/multiple-charmaps.err
  test/asm/multivalue-charmap.err
  test/asm/warn-numeric-string.err
Labels: enhancement, rgbasm

#1435 Implement state file output for RGBASM
  contrib/bash_compl/_rgbasm.bash
  contrib/bash_compl/_rgbgfx.bash
  contrib/zsh_compl/_rgbasm
  contrib/zsh_compl/_rgbgfx
  include/asm/charmap.hpp
  include/asm/output.hpp
  include/asm/symbol.hpp
  man/rgbasm.1
  src/asm/charmap.cpp
  src/asm/main.cpp
  src/asm/output.cpp
  src/asm/symbol.cpp
  src/gfx/main.cpp
  src/link/symbol.cpp
Labels: enhancement, rgbasm

#1443 Implement `-Wpurge=`
  contrib/bash_compl/_rgbasm.bash
  contrib/zsh_compl/_rgbasm
  include/asm/warning.hpp
  man/rgbasm.1
  man/rgbasm.5
  src/asm/symbol.cpp
  src/asm/warning.cpp
  test/asm/local-purge.err
  test/asm/purge-multiple.err
  test/asm/purge-ref.err
  test/asm/purge-refs.err
  test/asm/purge.err
  test/asm/sym-collision.err
  test/asm/trailing-commas.err
Labels: enhancement, rgbasm

#1448 Multiple fixes and enhancements to RPN behavior
  include/asm/rpn.hpp
  include/linkdefs.hpp
  man/rgbasm.5
  man/rgbds.5
  src/asm/parser.y
  src/asm/rpn.cpp
  src/link/patch.cpp
  test/asm/const-and.out
Labels: bug, enhancement, rgbasm, rgblink

#1449 Rephrase this warning to not be identical to another one
  src/asm/warning.cpp
  test/asm/warn-numeric-string.err
Labels: rgbasm

#1453 Error messages note when a symbol has been purged
  include/asm/symbol.hpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/asm/symbol.cpp
  test/asm/local-purge.err
  test/asm/sym-collision.err
Labels: enhancement, rgbasm

#1450 Implement `BITWIDTH` and `TZCOUNT` functions
  include/linkdefs.hpp
  man/rgbasm.5
  man/rgbds.5
  src/asm/lexer.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/link/patch.cpp
  test/asm/bit-functions.asm
  test/link/operators.asm
  test/link/operators.out.bin
Labels: enhancement, rgbasm, rgblink

#1458 Document the behavior of `FMOD`, and other man page cleanup
  man/rgbasm.5
Labels: docs, rgbasm

#1425 Fix RGBGFX reversal
  include/gfx/main.hpp
  src/gfx/main.cpp
  src/gfx/reverse.cpp
  test/gfx/.gitignore
  test/gfx/rgbgfx_test.cpp
Labels: bug, rgbgfx

#1459 Advise on how to use `-x` to make `-r` work
  src/gfx/reverse.cpp
Labels: enhancement, rgbgfx

#1455 Improve fixed-point documentation
  man/rgbasm.5
Labels: enhancement, docs, rgbasm

#1462 Fix constant expression detection functions
  src/asm/rpn.cpp
  test/asm/const-unknown.asm
Labels: bug, rgbasm

#1461 Build “fat binaries” for macOS
  .github/scripts/build_libpng.sh
  .github/scripts/install_deps.sh
  .github/scripts/mingw-w64-libpng-dev.sh
  .github/workflows/create-release-artifacts.yml
  .github/workflows/testing.yml
Labels: enhancement, builds

#1463 Comment the parsers better
  src/asm/lexer.cpp
  src/asm/parser.y
  src/link/script.y
Labels: rgbasm, refactoring

#1468 Allow mirroring only the X or Y axes
  contrib/bash_compl/_rgbgfx.bash
  contrib/zsh_compl/_rgbgfx
  include/gfx/main.hpp
  src/gfx/main.cpp
  src/gfx/process.cpp
Labels: enhancement, rgbgfx

#1475 Document `!cc` support alongside `HIGH(r16)` and `LOW(r16)` support
  man/gbz80.7
  man/rgbasm.5
Labels: docs, rgbasm

#1472 Test the RGBASM state file output
  src/asm/output.cpp
  test/asm/state-file/a.asm
  test/asm/state-file/a.dump.asm
  test/asm/test.sh
Labels: tests, rgbasm

#1474 Improve some documentation
  man/rgbasm.5
Labels: docs, rgbasm

#1476 Use a custom generic tagged union `Either` instead of `std::variant` for efficiency
  include/asm/fstack.hpp
  include/asm/lexer.hpp
  include/asm/rpn.hpp
  include/either.hpp
  include/file.hpp
  include/link/main.hpp
  include/link/symbol.hpp
  src/asm/fstack.cpp
  src/asm/lexer.cpp
  src/asm/parser.y
  src/asm/rpn.cpp
  src/link/main.cpp
  src/link/object.cpp
  src/link/output.cpp
  src/link/patch.cpp
  src/link/sdas_obj.cpp
  src/link/symbol.cpp
Labels: optimization

#1479 Test RGBLINK on SDCC object files
  test/link/sdcc/good/a.asm
  test/link/sdcc/good/b.c
  test/link/sdcc/good/b.rel
  test/link/sdcc/good/c.c
  test/link/sdcc/good/c.rel
  test/link/sdcc/good/out.err
  test/link/sdcc/good/ref.out.bin
  test/link/sdcc/good/ref.out.sym
  test/link/sdcc/good/script.link
  test/link/sdcc/no-script/a.asm
  test/link/sdcc/no-script/b.c
  test/link/sdcc/no-script/b.rel
  test/link/sdcc/no-script/out.err
  test/link/test.sh
Labels: tests, rgblink

#1473 Enable more testing of RGBGFX output
  CONTRIBUTING.md
  test/gfx/.gitignore
  test/gfx/crop.out.2bpp
  test/gfx/crop.out.pal
  test/gfx/empty_lines.out.2bpp
  test/gfx/empty_lines.out.pal
  test/gfx/full_gpl.out.2bpp
  test/gfx/full_gpl.out.attrmap
  test/gfx/full_gpl.out.pal
  test/gfx/full_gpl.out.tilemap
  test/gfx/full_hex.out.2bpp
  test/gfx/full_hex.out.attrmap
  test/gfx/full_hex.out.pal
  test/gfx/full_hex.out.tilemap
  test/gfx/multiple_manual_pals.out.2bpp
  test/gfx/multiple_manual_pals.out.pal
  test/gfx/none_round_trip.flags
  test/gfx/test.sh
Labels: tests, rgbgfx

#1486 Charmaps cannot map an empty string
  src/asm/charmap.cpp
  test/asm/charmap-empty.asm
  test/asm/charmap-empty.err
Labels: bug, rgbasm

#1490 Replace `unmangle` with `cygpath`
  .github/workflows/testing.yml
  Makefile
  test/CMakeLists.txt
  test/link/.gitignore
  test/link/test.sh
  test/link/unmangle.cpp
Labels: tests, rgblink
